[package]
name = "kotoconn-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "kotoconn"
path = "src/main.rs"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
kotoconn-daemon.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true

[dev-dependencies]
serde_json = "1"
