[package]
name = "kotoconn-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "kotoconn"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
kotoconn-daemon.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

[dev-dependencies]
serde_json.workspace = true
