use crate::{data::*, host, native::*};
use ts_rs::TS;

pub(crate) fn declarations() -> String {
    // These fail compilation when a handwritten native view no longer matches its methods.
    let _: fn(&IpAddr) -> u8 = IpAddr::version;
    let _: fn(&IpAddr, IpAddr) -> bool = IpAddr::equals;
    let _: fn(&IpAddr) -> bool = IpAddr::is_private;
    let _: fn(&IpAddr) -> bool = IpAddr::is_loopback;
    let _: fn(&IpAddr) -> bool = IpAddr::is_link_local;
    let _: fn(&IpAddr) -> bool = IpAddr::is_multicast;
    let _: fn(&IpAddr) -> bool = IpAddr::is_unspecified;
    let _: fn(&IpAddr) -> String = IpAddr::display;
    let _: fn(&Cidr, IpAddr) -> bool = Cidr::contains;
    let _: fn(&Cidr) -> String = Cidr::display;
    let _: fn(&Inbound, Inbound) -> bool = Inbound::equals;
    let _: fn(&Target) -> u16 = Target::port;
    let _: fn(&Target) -> Option<String> = Target::domain;
    let _: fn(&Target) -> Option<IpAddr> = Target::ip;

    let cfg = ts_rs::Config::default();
    let declarations = [
        IpAddr::decl(&cfg),
        Cidr::decl(&cfg),
        Target::decl(&cfg),
        Timeout::decl(&cfg),
        Port::decl(&cfg),
        Mtu::decl(&cfg),
        Byte::decl(&cfg),
        Milliseconds::decl(&cfg),
        Dialer::decl(&cfg),
        Inbound::decl(&cfg),
        Routing::decl(&cfg),
        Resolve::decl(&cfg),
        Dns::decl(&cfg),
        Request::decl(&cfg),
        Response::decl(&cfg),
        Decision::decl(&cfg),
        DnsResult::decl(&cfg),
        InboundImpl::decl(&cfg),
        OutboundImpl::decl(&cfg),
        Hysteria2InboundConfig::decl(&cfg),
        Hysteria2OutboundConfig::decl(&cfg),
        TlsClientConfig::decl(&cfg),
        TlsServerConfig::decl(&cfg),
        AnyTlsInboundConfig::decl(&cfg),
        AnyTlsOutboundConfig::decl(&cfg),
        HttpInboundConfig::decl(&cfg),
        Socks5InboundConfig::decl(&cfg),
        Shadowsocks2022InboundConfig::decl(&cfg),
        HttpOutboundConfig::decl(&cfg),
        NaiveInboundConfig::decl(&cfg),
        NaiveOutboundConfig::decl(&cfg),
        Shadowsocks2022OutboundConfig::decl(&cfg),
        Flow::decl(&cfg),
        SniffConfig::decl(&cfg),
        SniffProtocol::decl(&cfg),
        SniffResult::decl(&cfg),
        TransportProtocol::decl(&cfg),
        SocketAddr::decl(&cfg),
        DirectInboundConfig::decl(&cfg),
        TunAddress::decl(&cfg),
        TunInboundConfig::decl(&cfg),
        DirectOutboundConfig::decl(&cfg),
        Socks5OutboundConfig::decl(&cfg),
        InboundConfig::decl(&cfg),
        OutboundConfig::decl(&cfg),
        DialerConfig::decl(&cfg),
        crate::handler::Handler::<(), ()>::decl(&cfg),
    ];

    format!(
        "// Generated by kotoconn-script. Run pnpm run generate-bindings to update.\n{}\n{}export declare const kotoconn: Kotoconn;\n",
        declarations
            .into_iter()
            .map(|d| format!("export {d}"))
            .collect::<Vec<_>>()
            .join("\n"),
        host::Host::declaration(&cfg)
    )
}
