[package]
name = "kotoconn-daemon"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
kotoconn-config.workspace = true
kotoconn-script.workspace = true
tokio.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
futures-util.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
