[package]
name = "kotoconn-protocol"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tracing.workspace = true
kotoconn-config.workspace = true
anyhow.workspace = true
bytes.workspace = true
futures-util.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
