[package]
name = "kotoconn-typescript"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
oxc = { workspace = true, features = ["codegen", "semantic", "transformer"] }
thiserror.workspace = true

[dev-dependencies]
rquickjs = { workspace = true, features = ["macro", "loader", "futures"] }
